version: '3'

x-spark-common:
  &spark-common
  image: extending-spark:latest
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  environment:
    - SPARK_MODE=worker
    - SPARK_USER=spark
    - SPARK_MASTER_URL=spark://spark-master:7077
    - SPARK_WORKER_MEMORY=1G
    - SPARK_WORKER_CORES=1
    - SPARK_RPC_AUTHENTICATION_ENABLED=no
    - SPARK_RPC_ENCRYPTION_ENABLED=no
    - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
    - SPARK_SSL_ENABLED=no
  depends_on:
    - spark-master
  networks:
    - testnetwork

services:
  spark-master:
    image: extending-spark:latest
    hostname: spark-master
    container_name: spark-master
    user: root
    volumes:
      - ./jobs:/opt/bitnami/spark/jobs
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - "9090:8080"
      - "7070:7070"
    networks:
      - testnetwork

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1

  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2

networks:
  testnetwork: